using NUnit.Framework;
using System.Threading;

namespace UI.Tests
{
    [TestFixture]
    public class ReportsDashboardTests : CBUSATestBase
    {
        [TestCase]
        public void ClickNoReport()
        {
            var reportdashboard = homepage.ClickNcp("NCP Quarterly Rebate Report");
            Thread.Sleep(2000);
            reportdashboard.ClickNoReport("Automation Test Contract 1");
            Thread.Sleep(2000);
            reportdashboard.AcceptDialog();
            Thread.Sleep(3000);
            reportdashboard.WaitForSpinnerDisappear();
            Thread.Sleep(2000);
            Assert.AreEqual("Report Ready to Submit", reportdashboard.CheckStatus("Automation Test Contract 1"));
            Assert.AreEqual("1 of 3", reportdashboard.VerifyProgressBar());
            reportdashboard.VerifyEditButton("Automation Test Contract 1");
            reportdashboard.ClickEditOrContinue("Automation Test Contract 1");
            Thread.Sleep(2000);
            Assert.AreEqual(true, reportdashboard.GetProjectRadioStatus("Medullus Tower", "Nothing to report this quarter"));
            Assert.AreEqual(true, reportdashboard.GetProjectRadioStatus("Yewtree Lodge", "Nothing to report this quarter"));
            Assert.AreEqual(true, reportdashboard.GetProjectRadioStatus("Twelve Oaks", "Nothing to report this quarter"));
            Assert.AreEqual(true, reportdashboard.GetProjectRadioStatus("The RoseVille", "Nothing to report this quarter"));
            Assert.AreEqual(true, reportdashboard.GetProjectRadioStatus("Pine Valley", "Nothing to report this quarter"));
            reportdashboard.ClickAddProject();
            Thread.Sleep(2000);
            reportdashboard.ClickAddOrManageProjects();
            Thread.Sleep(2000);
            reportdashboard.InsertNumberOfProjects("1");
            Thread.Sleep(2000);
            reportdashboard.ClickAdd();
            Thread.Sleep(3000);
            reportdashboard.InsertProjectDetails(6, "Test Project 1", "Test Lot1", "Test Address1", "Kolkata", "kol123");
            Thread.Sleep(2000);
            reportdashboard.SaveProject();
            Thread.Sleep(2000);
            reportdashboard.ClickSetNoProjectStatus();
            reportdashboard.WaitLoading();
            reportdashboard.WaitForSpinnerDisappear();         
            Thread.Sleep(5000);
            Assert.AreEqual(6, reportdashboard.VerifyProjectRows());
            Assert.AreEqual(true, reportdashboard.VerifyProjects("Test Project 1 ,Test Lot1 ,Alabama ,Test Address1"));
            reportdashboard.SaveProject();
            Thread.Sleep(2000);
            reportdashboard.AcceptDialog();
            reportdashboard.WaitForSpinnerDisappear();
            reportdashboard.WaitLoading();
            Thread.Sleep(5000);
            Assert.AreEqual("Reporting in Progress", reportdashboard.CheckStatus("Automation Test Contract 1"));
            Assert.AreEqual("CONTINUE", reportdashboard.VerifyContinueButton("Automation Test Contract 1"));
            Assert.AreEqual("Not Started", reportdashboard.CheckStatus("Automation Test Contract 2"));
            Assert.AreEqual("SELECT PROJECTS", reportdashboard.VerifyContinueButton("Automation Test Contract 2"));
            Assert.AreEqual("Not Started", reportdashboard.CheckStatus("Automation Test Contract 3"));
            Assert.AreEqual("SELECT PROJECTS", reportdashboard.VerifyContinueButton("Automation Test Contract 3"));
            reportdashboard.ClickEditOrContinue("Automation Test Contract 2");
            reportdashboard.WaitLoading();
            Thread.Sleep(2000);
            Assert.AreEqual(false, reportdashboard.GetProjectRadioStatus("Test Project 1", "Nothing to report this quarter"));
            reportdashboard.ClickNCPQuaterlyRebate();
            reportdashboard.WaitLoading();
            reportdashboard.WaitForSpinnerDisappear();
            Thread.Sleep(5000);
            reportdashboard.ClickEditOrContinue("Automation Test Contract 3");
            reportdashboard.WaitLoading();
            Thread.Sleep(2000);
            Assert.AreEqual(false, reportdashboard.GetProjectRadioStatus("Test Project 1", "Nothing to report this quarter"));
            reportdashboard.ClickNCPQuaterlyRebate();
            reportdashboard.WaitLoading();
            reportdashboard.WaitForSpinnerDisappear();
            Thread.Sleep(5000);
            reportdashboard.ClickEditOrContinue("Automation Test Contract 1");
            reportdashboard.WaitLoading();
            Thread.Sleep(2000);
            reportdashboard.ClickProjectStatus("Test Project 1 ,Test Lot1 ,Alabama ,Test Address1", "Nothing to report this quarter");
            reportdashboard.ClickProjectStatus("Medullus Tower ,121 ,Texas ,Peach Tree Avenue", "Report units for this quarter");
            reportdashboard.ClickProjectStatus("Pine Valley ,B-166 ,Texas ,Riverside Road", "Report units for this quarter");
            reportdashboard.ClickProjectStatus("The RoseVille ,1337 ,Texas ,Metropolitan Highway", "Report units for this quarter");
            reportdashboard.ClickProjectStatus("Twelve Oaks ,337 ,Texas ,Peach Tree Avenue", "Report units for this quarter");
            reportdashboard.ClickProjectStatus("Yewtree Lodge ,9/B ,Texas ,The Crescent", "Report units for this quarter");
            reportdashboard.SaveProject();
            reportdashboard.WaitForSpinnerDisappear();
            reportdashboard.WaitLoading();
            Thread.Sleep(3000);
            reportdashboard.InsertTextInFullResponse("Medullus Tower", "Test Full Response");
            reportdashboard.InsertTextInFullResponse("Pine Valley", "Test Full Response 1");
            reportdashboard.Option("Pine Valley").SelectByText("Test Option 2");
            reportdashboard.InsertTextInFullResponse("The RoseVille", "Test Full Response 2");
            reportdashboard.Option("The RoseVille").SelectByText("Test Option 3");
            reportdashboard.InsertTextInFullResponse("Twelve Oaks", "Test Full Response 3");
            reportdashboard.Option("Twelve Oaks").SelectByText("Test Option 2");
            reportdashboard.InsertTextInFullResponse("Yewtree Lodge", "Test Full Response 4");
            Thread.Sleep(2000);
            reportdashboard.SaveResponse();
            reportdashboard.WaitForSpinnerDisappear();
            reportdashboard.WaitLoading();
            reportdashboard.WaitForSpinnerDisappear();
            Thread.Sleep(5000);
            Assert.AreEqual("Report Ready to Submit", reportdashboard.CheckStatus("Automation Test Contract 1"));
            reportdashboard.VerifyEditButton("Automation Test Contract 1");
            reportdashboard.ClickEditOrContinue("Automation Test Contract 1");
            reportdashboard.WaitLoading();
            Thread.Sleep(2000);
            Assert.AreEqual(true, reportdashboard.GetProjectRadioStatus("Test Project 1", "Nothing to report this quarter"));
            Assert.AreEqual(true, reportdashboard.GetProjectRadioStatus("Medullus Tower", "Report units for this quarter"));
            Assert.AreEqual(true, reportdashboard.GetProjectRadioStatus("Pine Valley", "Report units for this quarter"));
            Assert.AreEqual(true, reportdashboard.GetProjectRadioStatus("The RoseVille", "Report units for this quarter"));
            Assert.AreEqual(true, reportdashboard.GetProjectRadioStatus("Twelve Oaks", "Report units for this quarter"));
            Assert.AreEqual(true, reportdashboard.GetProjectRadioStatus("Yewtree Lodge", "Report units for this quarter"));
            reportdashboard.SaveProject();
            reportdashboard.WaitForSpinnerDisappear();
            reportdashboard.WaitLoading();
            Thread.Sleep(3000);
            Assert.AreEqual("Test Full Response", reportdashboard.VerifyFullResponse("Medullus Tower"));
            Assert.AreEqual("Test Option 1", reportdashboard.VerifyPartialResponse("Medullus Tower"));
            Assert.AreEqual("Test Full Response 1", reportdashboard.VerifyFullResponse("Pine Valley"));
            Assert.AreEqual("Test Option 2", reportdashboard.VerifyPartialResponse("Pine Valley"));
            Assert.AreEqual("Test Full Response 2", reportdashboard.VerifyFullResponse("The RoseVille"));
            Assert.AreEqual("Test Option 3", reportdashboard.VerifyPartialResponse("The RoseVille"));
            Assert.AreEqual("Test Full Response 3", reportdashboard.VerifyFullResponse("Twelve Oaks"));
            Assert.AreEqual("Test Option 2", reportdashboard.VerifyPartialResponse("Twelve Oaks"));
            Assert.AreEqual("Test Full Response 4", reportdashboard.VerifyFullResponse("Yewtree Lodge"));
            Assert.AreEqual("Test Option 1", reportdashboard.VerifyPartialResponse("Yewtree Lodge"));
            reportdashboard.SaveResponse();
            reportdashboard.WaitForSpinnerDisappear();
            reportdashboard.WaitLoading();
            reportdashboard.WaitForSpinnerDisappear();
            Thread.Sleep(5000);
            reportdashboard.ClickEditOrContinue("Automation Test Contract 2");
            reportdashboard.WaitLoading();
            reportdashboard.ClickPreviouslyReportedProjects();
            reportdashboard.WaitForSpinnerDisappear();
            Thread.Sleep(2000);
            reportdashboard.CheckReopenProjects("Pine Valley");
            reportdashboard.CheckReopenProjects("The RoseVille");
            reportdashboard.ClickRepoen();
            reportdashboard.WaitForSpinnerDisappear();
            Assert.AreEqual(true, reportdashboard.VerifyProjects("The RoseVille ,1337 ,Texas ,Metropolitan Highway"));
            Assert.AreEqual(true, reportdashboard.VerifyProjects("Pine Valley ,B-166 ,Texas ,Riverside Road"));
            reportdashboard.ClickProjectStatus("Medullus Tower ,121 ,Texas ,Peach Tree Avenue", "Nothing to report this quarter");
            reportdashboard.SaveProject();
            reportdashboard.AcceptDialog();
            reportdashboard.WaitForSpinnerDisappear();
            //Thread.Sleep(2000);
            //reportdashboard.SaveResponse();
            reportdashboard.WaitLoading();
            reportdashboard.WaitForSpinnerDisappear();
            Thread.Sleep(5000);
            reportdashboard.ClickEditOrContinue("Automation Test Contract 2");
            reportdashboard.WaitLoading();
            Thread.Sleep(2000);
            Assert.AreEqual(false, reportdashboard.VerifyProjects("The RoseVille ,1337 ,Texas ,Metropolitan Highway"));
            Assert.AreEqual(false, reportdashboard.VerifyProjects("Pine Valley ,B-166 ,Texas ,Riverside Road"));
            reportdashboard.ClickPreviouslyReportedProjects();
            reportdashboard.WaitForSpinnerDisappear();
            Thread.Sleep(2000);
            reportdashboard.CheckReopenProjects("Pine Valley");
            reportdashboard.CheckReopenProjects("The RoseVille");
            reportdashboard.ClickRepoen();
            reportdashboard.WaitForSpinnerDisappear();
            Thread.Sleep(2000);
            reportdashboard.ClickProjectStatus("Pine Valley ,B-166 ,Texas ,Riverside Road", "Report units for this quarter");
            reportdashboard.ClickProjectStatus("The RoseVille ,1337 ,Texas ,Metropolitan Highway", "Nothing to report this quarter");
            reportdashboard.SaveProject();
            reportdashboard.WaitForSpinnerDisappear();
            reportdashboard.WaitLoading();
            Thread.Sleep(3000);
            reportdashboard.InsertTextInFullResponse("Pine Valley", "Testing Reopen Response");
            Thread.Sleep(2000);
            reportdashboard.SaveResponse();
            reportdashboard.WaitForSpinnerDisappear();
            reportdashboard.WaitLoading();
            reportdashboard.WaitForSpinnerDisappear();
            Thread.Sleep(5000);
            reportdashboard.ClickEditOrContinue("Automation Test Contract 2");
            reportdashboard.WaitLoading();
            reportdashboard.WaitForSpinnerDisappear();
            Thread.Sleep(2000);
            reportdashboard.GetProjectRadioStatus("Pine Valley", "Report units for this quarter");
            reportdashboard.GetProjectRadioStatus("The RoseVille", "Nothing to report this quarter");
            reportdashboard.SaveProject();
            reportdashboard.WaitForSpinnerDisappear();
            reportdashboard.WaitLoading();
            reportdashboard.WaitForSpinnerDisappear();
            Thread.Sleep(2000);
            Assert.AreEqual("Testing Reopen Response", reportdashboard.VerifyFullResponse("Pine Valley"));
            reportdashboard.SaveResponse();
            reportdashboard.WaitForSpinnerDisappear();
            reportdashboard.WaitLoading();
            reportdashboard.WaitForSpinnerDisappear();
            Thread.Sleep(5000);
            reportdashboard.ClickEditOrContinue("Automation Test Contract 2");
            reportdashboard.WaitLoading();
            reportdashboard.WaitForSpinnerDisappear();
            Thread.Sleep(3000);
            reportdashboard.ClickProjectStatus("Test Project 1 ,Test Lot1 ,Alabama ,Test Address1", "Nothing to report this quarter");
            reportdashboard.ClickProjectStatus("Medullus Tower ,121 ,Texas ,Peach Tree Avenue", "Report units for this quarter");
            reportdashboard.ClickProjectStatus("Pine Valley ,B-166 ,Texas ,Riverside Road", "Report units for this quarter");
            reportdashboard.ClickProjectStatus("The RoseVille ,1337 ,Texas ,Metropolitan Highway", "Report units for this quarter");
            reportdashboard.ClickProjectStatus("Yewtree Lodge ,9/B ,Texas ,The Crescent", "Nothing to report this quarter");
            reportdashboard.SaveProject();
            reportdashboard.WaitForSpinnerDisappear();
            reportdashboard.WaitLoading();
            Thread.Sleep(3000);
            reportdashboard.InsertTextInFullResponse("Medullus Tower", "Test Reopen Response 1");
            reportdashboard.Option("Medullus Tower").SelectByText("50 to 100");
            reportdashboard.Option("Pine Valley").SelectByText("More than 100");
            reportdashboard.InsertTextInFullResponse("The RoseVille", "Test Reopen Response 2");
            Thread.Sleep(2000);
            reportdashboard.SaveResponse();
            reportdashboard.WaitForSpinnerDisappear();
            reportdashboard.WaitLoading();
            reportdashboard.WaitForSpinnerDisappear();
            Thread.Sleep(4000);
            Assert.AreEqual("Report Ready to Submit", reportdashboard.CheckStatus("Automation Test Contract 2"));
            reportdashboard.VerifyEditButton("Automation Test Contract 2");
            Assert.AreEqual("2 of 3", reportdashboard.VerifyProgressBar());
            reportdashboard.ClickEditOrContinue("Automation Test Contract 3");
            reportdashboard.WaitLoading();
            reportdashboard.WaitForSpinnerDisappear();
            reportdashboard.ClickProjectStatus("Medullus Tower ,121 ,Texas ,Peach Tree Avenue", "Never report for this project");
            reportdashboard.ClickProjectStatus("Yewtree Lodge ,9/B ,Texas ,The Crescent", "Nothing to report this quarter");
            reportdashboard.ClickProjectStatus("Pine Valley ,B-166 ,Texas ,Riverside Road", "Never report for this project");
            reportdashboard.ClickProjectStatus("Test Project 1 ,Test Lot1 ,Alabama ,Test Address1", "Nothing to report this quarter");
            reportdashboard.ClickProjectStatus("The RoseVille ,1337 ,Texas ,Metropolitan Highway", "Never report for this project");
            reportdashboard.ClickProjectStatus("Twelve Oaks ,337 ,Texas ,Peach Tree Avenue", "Nothing to report this quarter");
            reportdashboard.SaveProject();
            reportdashboard.AcceptDialog();
            reportdashboard.WaitForSpinnerDisappear();
            Thread.Sleep(5000);
            reportdashboard.AcceptDialog();
            Assert.AreEqual("Report Ready to Submit", reportdashboard.CheckStatus("Automation Test Contract 3"));           
            Thread.Sleep(5000);
            reportdashboard.ClickEditOrContinue("Automation Test Contract 3");
            reportdashboard.WaitLoading();
            reportdashboard.WaitForSpinnerDisappear();
            Thread.Sleep(3000);
            reportdashboard.ClickAddProject();
            Thread.Sleep(2000);
            reportdashboard.ClickAddOrManageProjects();
            Thread.Sleep(2000);
            reportdashboard.InsertNumberOfProjects("1");
            Thread.Sleep(2000);
            reportdashboard.ClickAdd();
            Thread.Sleep(2000);
            reportdashboard.InsertProjectDetails(7, "Test Project 2", "Test Lot2", "Test Address2", "Chicago", "USA");
            Thread.Sleep(2000);
            reportdashboard.SaveProject();
            reportdashboard.ClickSetYesProjectStatus();
            reportdashboard.WaitForSpinnerDisappear();
            reportdashboard.WaitLoading();
            Thread.Sleep(3000);
            //reportdashboard.ClickProjectStatus("Test Project 2 ,Test Lot2 ,Alabama ,Test Address2", "Nothing to report this quarter");
            reportdashboard.SaveProject();
            reportdashboard.AcceptDialog();
            reportdashboard.WaitForSpinnerDisappear();
            //reportdashboard.WaitLoading();
            Thread.Sleep(6000);
            reportdashboard.AcceptDialog();
            reportdashboard.ClickEditOrContinue("Automation Test Contract 3");
            reportdashboard.WaitLoading();
            reportdashboard.WaitForSpinnerDisappear();
            Thread.Sleep(3000);
            reportdashboard.GetProjectRadioStatus("Test Project 2", "Nothing to report this quarter");
            reportdashboard.ClickNCPQuaterlyRebate();
            reportdashboard.WaitForSpinnerDisappear();
            Thread.Sleep(6000);
            reportdashboard.AcceptDialog();           
            reportdashboard.ClickEditOrContinue("Automation Test Contract 2");
            reportdashboard.WaitLoading();
            reportdashboard.WaitForSpinnerDisappear();
            Thread.Sleep(3000);
            reportdashboard.GetProjectRadioStatus("Test Project 2", "Nothing to report this quarter");
            reportdashboard.ClickNCPQuaterlyRebate();
            reportdashboard.WaitForSpinnerDisappear();
            Thread.Sleep(6000);
            reportdashboard.AcceptDialog();          
            reportdashboard.ClickEditOrContinue("Automation Test Contract 1");
            reportdashboard.WaitLoading();
            reportdashboard.WaitForSpinnerDisappear();
            Thread.Sleep(3000);
            reportdashboard.GetProjectRadioStatus("Test Project 2", "Nothing to report this quarter");
            reportdashboard.ClickNCPQuaterlyRebate();
            reportdashboard.WaitForSpinnerDisappear();
            Thread.Sleep(6000);
            reportdashboard.AcceptDialog();           
            reportdashboard.ClickFinalSubmitRebateReport();
            reportdashboard.WaitForSpinnerDisappear();
            //reportdashboard.AcceptDialog();
            //Thread.Sleep(2000);
            reportdashboard.ClickConfirmReport();
            reportdashboard.WaitLoading();
            Thread.Sleep(3000);
            reportdashboard.ClickNCPQuaterlyRebate();
            reportdashboard.WaitLoading();
            reportdashboard.WaitForSpinnerDisappear();
            Assert.AreEqual("Report Submitted", reportdashboard.VerifyProgressBar());
            reportdashboard.VerifyEditButtonDisabled("Automation Test Contract 1");
            reportdashboard.VerifyEditButtonDisabled("Automation Test Contract 2");
            reportdashboard.VerifyEditButtonDisabled("Automation Test Contract 3");
            reportdashboard.ClickNcpRebateReportHistory();
            reportdashboard.WaitLoading();
            reportdashboard.WaitForSpinnerDisappear();
            Thread.Sleep(2000);
            reportdashboard.ClickViewHistoricalReports("Automation Test Contract 1");
            reportdashboard.WaitLoading();
            reportdashboard.WaitForSpinnerDisappear();
            var responsecontract1 = reportdashboard.ClickPreview("Q3-2018");
            responsecontract1.WaitLoading();
            Thread.Sleep(2000);
            Assert.AreEqual("Test Full Response", responsecontract1.VerifyFullResponse("Medullus Tower"));
            Assert.AreEqual("Test Option 1", responsecontract1.VerifyPartialResponse("Medullus Tower"));
            Assert.AreEqual("Test Full Response 1", responsecontract1.VerifyFullResponse("Pine Valley"));
            Assert.AreEqual("Test Option 2", responsecontract1.VerifyPartialResponse("Pine Valley"));
            Assert.AreEqual("Test Full Response 2", responsecontract1.VerifyFullResponse("The RoseVille"));
            Assert.AreEqual("Test Option 3", responsecontract1.VerifyPartialResponse("The RoseVille"));
            Assert.AreEqual("Test Full Response 3", responsecontract1.VerifyFullResponse("Twelve Oaks"));
            Assert.AreEqual("Test Option 2", responsecontract1.VerifyPartialResponse("Twelve Oaks"));
            Assert.AreEqual("Test Full Response 4", responsecontract1.VerifyFullResponse("Yewtree Lodge"));
            Assert.AreEqual("Test Option 1", responsecontract1.VerifyPartialResponse("Yewtree Lodge"));
            reportdashboard.ClickNCPQuaterlyRebate();
            reportdashboard.WaitLoading();
            reportdashboard.WaitForSpinnerDisappear();
            reportdashboard.ClickNcpRebateReportHistory();
            reportdashboard.WaitLoading();
            reportdashboard.WaitForSpinnerDisappear();
            Thread.Sleep(2000);
            reportdashboard.ClickViewHistoricalReports("Automation Test Contract 2");
            reportdashboard.WaitLoading();
            reportdashboard.WaitForSpinnerDisappear();
            var responsecontract2 = reportdashboard.ClickPreview("Q1-2018");
            responsecontract2.WaitLoading();
            Thread.Sleep(2000);
            Assert.AreEqual("Test Answer 1", responsecontract1.VerifyFullResponse("Pine Valley"));
            Assert.AreEqual("Test Option 1", responsecontract1.VerifyPartialResponse("Pine Valley"));
            Assert.AreEqual("Test Answer 2", responsecontract1.VerifyFullResponse("Twelve Oaks"));
            Assert.AreEqual("Test Option 2", responsecontract1.VerifyPartialResponse("Twelve Oaks"));
            Assert.AreEqual("Test Answer 3", responsecontract1.VerifyFullResponse("The RoseVille"));
            Assert.AreEqual("Test Option 3", responsecontract1.VerifyPartialResponse("The RoseVille"));
            reportdashboard.ClickNCPQuaterlyRebate();
            reportdashboard.WaitLoading();
            reportdashboard.WaitForSpinnerDisappear();
            reportdashboard.ClickNcpRebateReportHistory();
            reportdashboard.WaitLoading();
            reportdashboard.WaitForSpinnerDisappear();
            Thread.Sleep(2000);
            reportdashboard.ClickViewHistoricalReports("Automation Test Contract 2");
            reportdashboard.WaitLoading();
            reportdashboard.WaitForSpinnerDisappear();
            var responsecontracts2 = reportdashboard.ClickPreview("Q3-2018");
            responsecontract2.WaitLoading();
            Thread.Sleep(2000);
            Assert.AreEqual("Testing Reopen Response", responsecontracts2.VerifyFullResponse("Pine Valley"));
            Assert.AreEqual("More than 100", responsecontracts2.VerifyPartialResponse("Pine Valley"));
            Assert.AreEqual("Test Reopen Response 2", responsecontracts2.VerifyFullResponse("The RoseVille"));
            Assert.AreEqual("1 to 50", responsecontracts2.VerifyPartialResponse("The RoseVille"));
            Assert.AreEqual("Test Reopen Response 1", responsecontracts2.VerifyFullResponse("Medullus Tower"));
            Assert.AreEqual("50 to 100", responsecontracts2.VerifyPartialResponse("Medullus Tower"));
            reportdashboard.ClickNCPQuaterlyRebate();
            reportdashboard.WaitLoading();
            reportdashboard.WaitForSpinnerDisappear();
            reportdashboard.ClickNcpRebateReportHistory();
            reportdashboard.WaitLoading();
            reportdashboard.WaitForSpinnerDisappear();
            Thread.Sleep(2000);
            reportdashboard.ClickViewHistoricalReports("Automation Test Contract 3");
            reportdashboard.WaitLoading();
            reportdashboard.WaitForSpinnerDisappear();
            Assert.AreEqual("No record to view detail", reportdashboard.VerifyClickPreview("Q3-2018"));
        }
    }
}
