CREATE TABLE [dbo].[TblContractBuilderAssociation] (
    [Id]             BIGINT         NULL,
    [Survey ID]      BIGINT         NULL,
    [Survey Name]    NVARCHAR (500) NULL,
    [Builder ID]     BIGINT         NULL,
    [Company Name]   NVARCHAR (500) NULL,
    [Contract State] NVARCHAR (500) NULL,
    [Contract ID]    BIGINT         NULL,
    [Contract Name]  NVARCHAR (500) NULL,
    [IsJoin]         NVARCHAR (255) NULL,
    [F10]            NVARCHAR (255) NULL,
    [F11]            NVARCHAR (255) NULL,
    [F12]            NVARCHAR (255) NULL,
    [F13]            NVARCHAR (255) NULL,
    [F14]            NVARCHAR (255) NULL,
    [F15]            NVARCHAR (255) NULL,
    [F16]            NVARCHAR (255) NULL,
    [F17]            NVARCHAR (255) NULL,
    [F18]            NVARCHAR (255) NULL,
    [F19]            NVARCHAR (255) NULL,
    [F20]            NVARCHAR (255) NULL,
    [F21]            NVARCHAR (255) NULL,
    [F22]            NVARCHAR (255) NULL,
    [F23]            NVARCHAR (255) NULL,
    [F24]            NVARCHAR (255) NULL,
    [F25]            NVARCHAR (255) NULL,
    [F26]            NVARCHAR (255) NULL,
    [F27]            NVARCHAR (255) NULL
);

