// <auto-generated />
namespace CBUSA.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatetableconstructformula : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatetableconstructformula));
        
        string IMigrationMetadata.Id
        {
            get { return "201702221351564_update table construct formula"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
